=== legras/uav3i/Paramétrage Paparazzi/Schéma/flight_plan.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Generated from Paparazzi flight plan DTD for JAXB classes generation.
  Note: DTD file comes from 5.0.2 version.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="flight_plan">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="header"/>
        <xs:element ref="waypoints"/>
        <xs:element minOccurs="0" ref="sectors"/>
        <xs:element minOccurs="0" ref="includes"/>
        <xs:element minOccurs="0" ref="exceptions"/>
        <xs:element ref="blocks"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.flight_plan"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="procedure">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="param"/>
        <xs:element minOccurs="0" ref="header"/>
        <xs:element minOccurs="0" ref="waypoints"/>
        <xs:element minOccurs="0" ref="sectors"/>
        <xs:element minOccurs="0" ref="exceptions"/>
        <xs:element minOccurs="0" ref="blocks"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="header" type="xs:string"/>
  <xs:element name="waypoints">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="waypoint"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.waypoints"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="waypoint">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.waypoint"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sectors">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="sector"/>
        <xs:element ref="kml"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="sector">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="corner"/>
        <xs:element ref="corner"/>
        <xs:element maxOccurs="unbounded" ref="corner"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.sector"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="corner">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.corner"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="kml">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.kml"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="includes">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="include"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="exceptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="exception"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="blocks">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="block"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="block">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="exception"/>
        <xs:element ref="while"/>
        <xs:element ref="heading"/>
        <xs:element ref="attitude"/>
        <xs:element ref="go"/>
        <xs:element ref="xyz"/>
        <xs:element ref="set"/>
        <xs:element ref="call"/>
        <xs:element ref="circle"/>
        <xs:element ref="deroute"/>
        <xs:element ref="stay"/>
        <xs:element ref="follow"/>
        <xs:element ref="survey_rectangle"/>
        <xs:element ref="for"/>
        <xs:element ref="return"/>
        <xs:element ref="eight"/>
        <xs:element ref="oval"/>
        <xs:element ref="home"/>
        <xs:element ref="path"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.block"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="arg"/>
        <xs:element ref="with"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.include"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="arg">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.arg"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="with">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.with"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="while">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="exception"/>
        <xs:element ref="while"/>
        <xs:element ref="heading"/>
        <xs:element ref="attitude"/>
        <xs:element ref="go"/>
        <xs:element ref="xyz"/>
        <xs:element ref="set"/>
        <xs:element ref="call"/>
        <xs:element ref="circle"/>
        <xs:element ref="deroute"/>
        <xs:element ref="stay"/>
        <xs:element ref="follow"/>
        <xs:element ref="survey_rectangle"/>
        <xs:element ref="for"/>
        <xs:element ref="return"/>
        <xs:element ref="eight"/>
        <xs:element ref="oval"/>
        <xs:element ref="path"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.while"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="for">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="exception"/>
        <xs:element ref="while"/>
        <xs:element ref="heading"/>
        <xs:element ref="attitude"/>
        <xs:element ref="go"/>
        <xs:element ref="xyz"/>
        <xs:element ref="set"/>
        <xs:element ref="call"/>
        <xs:element ref="circle"/>
        <xs:element ref="deroute"/>
        <xs:element ref="stay"/>
        <xs:element ref="follow"/>
        <xs:element ref="survey_rectangle"/>
        <xs:element ref="for"/>
        <xs:element ref="return"/>
        <xs:element ref="eight"/>
        <xs:element ref="oval"/>
        <xs:element ref="path"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.for"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="exception">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.exception"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="heading">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.heading"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attitude">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.attitude"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="go">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.go"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="xyz">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.xyz"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="set">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.set"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="call">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.call"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="circle">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.circle"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="home">
    <xs:complexType/>
  </xs:element>
  <xs:element name="eight">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.eight"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="oval">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.oval"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="survey_rectangle">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.survey_rectangle"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="deroute">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.deroute"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="stay">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.stay"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="follow">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.follow"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.param"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="return">
    <xs:complexType/>
  </xs:element>
  <xs:element name="path">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.path"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.flight_plan">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="lat0" use="required"/>
    <xs:attribute name="lon0" use="required"/>
    <xs:attribute name="max_dist_from_home" use="required"/>
    <xs:attribute name="ground_alt" use="required"/>
    <xs:attribute name="security_height" use="required"/>
    <xs:attribute name="alt" use="required"/>
    <xs:attribute name="qfu"/>
    <xs:attribute name="home_mode_height"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.waypoints">
    <xs:attribute name="utm_x0"/>
    <xs:attribute name="utm_y0"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.waypoint">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="x"/>
    <xs:attribute name="y"/>
    <xs:attribute name="lat"/>
    <xs:attribute name="lon"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="height"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.sector">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="color"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.corner">
    <xs:attribute name="name" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.kml">
    <xs:attribute name="file" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.block">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="pre_call"/>
    <xs:attribute name="post_call"/>
    <xs:attribute name="strip_button"/>
    <xs:attribute name="strip_icon"/>
    <xs:attribute name="group"/>
    <xs:attribute name="key"/>
    <xs:attribute name="description"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.exception">
    <xs:attribute name="cond" use="required"/>
    <xs:attribute name="deroute" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.while">
    <xs:attribute name="cond"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.for">
    <xs:attribute name="var" use="required"/>
    <xs:attribute name="from" use="required"/>
    <xs:attribute name="to" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.heading">
    <xs:attribute name="course" use="required"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="height"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="until" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.attitude">
    <xs:attribute name="roll" use="required"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="height"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="until"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.go">
    <xs:attribute name="wp" use="required"/>
    <xs:attribute name="wp_qdr"/>
    <xs:attribute name="wp_dist"/>
    <xs:attribute name="from"/>
    <xs:attribute name="from_qdr"/>
    <xs:attribute name="from_dist"/>
    <xs:attribute name="hmode"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="height"/>
    <xs:attribute name="approaching_time"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="until"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.path">
    <xs:attribute name="wpts" use="required"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="approaching_time"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="climb"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.set">
    <xs:attribute name="var" use="required"/>
    <xs:attribute name="value" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.call">
    <xs:attribute name="fun" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.follow">
    <xs:attribute name="ac_id" use="required"/>
    <xs:attribute name="distance" use="required"/>
    <xs:attribute name="height" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.xyz">
    <xs:attribute name="radius"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.circle">
    <xs:attribute name="wp" use="required"/>
    <xs:attribute name="wp_qdr"/>
    <xs:attribute name="wp_dist"/>
    <xs:attribute name="radius" use="required"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="height"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="until"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.eight">
    <xs:attribute name="center" use="required"/>
    <xs:attribute name="turn_around" use="required"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="until"/>
    <xs:attribute name="radius" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.oval">
    <xs:attribute name="p1" use="required"/>
    <xs:attribute name="p2" use="required"/>
    <xs:attribute name="radius" use="required"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="pitch"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="until"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.survey_rectangle">
    <xs:attribute name="grid" use="required"/>
    <xs:attribute name="orientation"/>
    <xs:attribute name="wp1" use="required"/>
    <xs:attribute name="wp2" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.stay">
    <xs:attribute name="wp" use="required"/>
    <xs:attribute name="vmode"/>
    <xs:attribute name="throttle"/>
    <xs:attribute name="climb"/>
    <xs:attribute name="alt"/>
    <xs:attribute name="until"/>
    <xs:attribute name="height"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.deroute">
    <xs:attribute name="block" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.include">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="procedure" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.arg">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="value" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.with">
    <xs:attribute name="from" use="required"/>
    <xs:attribute name="to" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.param">
    <xs:attribute name="name" use="required"/>
    <xs:attribute name="default_value"/>
  </xs:attributeGroup>
</xs:schema>

=== legras/uav3i/Parametrage Paparazzi/Plans de vol/uav3i_rotterdam.xml
<?xml version="1.0" encoding="UTF-8"?>

<flight_plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="flight_plan.xsd"
             alt="100"
             ground_alt="0"
             lat0="51.935655"
             lon0="4.002431"
             max_dist_from_home="5000"
             name="Zone approximative de la démo néerlandaise - Rotterdam"
             security_height="25">

  <header>
    #include "subsystems/navigation/nav_line.h"
    #include "subsystems/datalink/datalink.h"
  </header>
  
  <waypoints>
    <!--
      Waypoint [1] : STDBY
      Waypoint [2] : 1
      Waypoint [3] : 2
      Waypoint [4] : MOB
      Waypoint [5] : S1
      Waypoint [6] : S2
      Waypoint [7] : CIRCLE_CENTER
      Waypoint [8] : AF
      Waypoint [9] : TD
      Waypoint [10] : CLIMB
	-->
    <waypoint name="HOME"          x="0" y="0"/>
    <waypoint name="STDBY"         x="627.6"  y="222.8"/>
    <waypoint name="1"             x="2765.9" y="1292.5"/>
    <waypoint name="2"             x="3688.5" y="686.2"/>
    <waypoint name="MOB"           x="400.9"  y="-1062.0"/>
    <waypoint name="S1"            x="3078.4" y="2251.9"/>
    <waypoint name="S2"            x="4101.5" y="1276.9"/>
    <waypoint name="CIRCLE_CENTER" x="3000.0" y="2000.0"/>
    <waypoint alt="215.0" name="AF" x="-94.6" y="202.1"/>
    <waypoint alt="185.0" name="TD" x="-13.0" y="33.8"/>
    <waypoint name="CLIMB" x="-114.5" y="162.3"/>
  </waypoints>
  
  <exceptions/>
  
  <blocks>
    <!--
      Block [0] : Wait GPS
      Block [1] : Takeoff
      Block [2] : Standby
      Block [3] : MOB
      Block [4] : Line 1-2
      Block [5] : Survey S1-S2
      Block [6] : Circle
      Block [7] : final
    -->
    <block name="Wait GPS">
      <set value="1" var="kill_throttle"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block group="home" key="t" name="Takeoff" strip_button="Takeoff (wp CLIMB)" strip_icon="takeoff.png">
      <set value="0" var="kill_throttle"/>
      <go from="HOME" pitch="15" throttle="1.0" vmode="throttle" wp="STDBY"/>
    </block>
    <block group="home" key="[Control]a" name="Standby" strip_button="Standby" strip_icon="home.png">
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block group="base_pattern" name="MOB" strip_button="Turn around here" strip_icon="mob.png">
      <call fun="NavSetWaypointHere(WP_MOB)"/>
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <circle radius="nav_radius" wp="MOB"/>
    </block>
    <block group="extra_pattern" name="Line 1-2" strip_button="Line (wp 1-2)" strip_icon="line.png">
      <call fun="nav_line_init()"/>
      <call fun="nav_line(WP_1, WP_2, nav_radius)"/>
    </block>
    <block group="extra_pattern" name="Survey S1-S2" strip_button="Survey (wp S1-S2)" strip_icon="survey.png">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>
    <block name="Circle">
      <circle radius="nav_radius" wp="CIRCLE_CENTER"/>
    </block>
    <block name="final">
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>
  </blocks>
  
</flight_plan>
